server:
  port: 8082
  error:
    include-message: always

spring:
  profiles:
    active: default
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer-service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  swagger-ui:
    path: /customer/swagger
  api-docs:
    path: /customer/v3/api-docs

---
spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: http://kafka-service:9092