kind: Deployment
apiVersion: apps/v1
metadata:
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: kafka
          image: batugokce/customer-service:0.0.1
          ports:
            - containerPort: 8082
          env:
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=test"